version = 1

[[analyzers]]
name = "python"
exclude_patterns = [
  "packages/**"
]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "ruff"
